const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let config=null,account=null,stage='email',address='',phone='',captchaToken='',captchaWidget;
const message=(text,error=false)=>{$('#account-message').textContent=text;$('#account-message').classList.toggle('error',error)};
async function api(path,body){const r=await fetch('./api/'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok){const error=Object.assign(Error(data.error||'Please try again.'),{status:r.status});throw error}return data}
const date=stamp=>stamp?new Date(stamp*1000).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'}):'—';
const links=()=>config?`<a href="${esc(config.terms)}" target="_blank" rel="noopener">Terms</a><a href="${esc(config.privacy)}" target="_blank" rel="noopener">Privacy</a><a href="${esc(config.refund)}" target="_blank" rel="noopener">Refund policy</a><a href="mailto:${esc(config.support)}">Contact support</a>`:'';
function steps(){return `<ol class="account-steps" aria-label="Account setup"><li ${stage.startsWith('email')?'aria-current="step"':''}>1. Email</li><li ${stage.startsWith('phone')?'aria-current="step"':''}>2. Phone</li><li ${stage==='checkout'?'aria-current="step"':''}>3. Your trial</li></ol>`}
function render(){
  const disabled=!config?'disabled':'';let html='';
  if(stage==='email')html=`${steps()}<h2>Start something worth building.</h2><p>New here or returning? We’ll send a code to your email. No password to remember.</p><form data-form="email"><label for="email">Email address</label><input id="email" name="email" type="email" autocomplete="email" required maxlength="254" placeholder="you@example.com" ${disabled}><div id="captcha"></div><button class="button primary" ${disabled}>Continue with email →</button></form><small>By continuing, you agree to the terms and acknowledge the privacy policy. Billing consent comes separately at checkout.</small>${!config?'<a class="button ghost" style="margin-top:18px" href="./">Try the three samples</a>':''}`;
  if(stage==='email-code')html=`${steps()}<h2>Check your inbox.</h2><p>Enter the code sent to <strong>${esc(address)}</strong>.</p><form data-form="email-code"><label for="code">Email code</label><input id="code" name="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6,10}" minlength="6" maxlength="10" required><button class="button primary">Verify email →</button></form><button class="textbutton" data-action="email-again">Change email or request another code</button>`;
  if(stage==='phone')html=`${steps()}<h2>One number. One account.</h2><p>Your email is verified. Add your mobile number to finish setting up your account.</p><form data-form="phone"><label for="phone">Mobile number with country code</label><input id="phone" name="phone" type="tel" autocomplete="tel" required placeholder="+1 415 555 0123" maxlength="30"><small>We’ll text a verification code. Message and data rates may apply. This does not opt you into marketing texts.</small><button class="button primary">Send verification code →</button></form><button class="textbutton" data-action="logout">Sign out</button>`;
  if(stage==='phone-code')html=`${steps()}<h2>Check your phone.</h2><p>Enter the code sent to <strong>${esc(phone)}</strong>.</p><form data-form="phone-code"><label for="code">SMS code</label><input id="code" name="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6,10}" minlength="6" maxlength="10" required><button class="button primary">Verify phone →</button></form><button class="textbutton" data-action="phone-again">Change number or request another code</button>`;
  if(stage==='checkout')html=`${steps()}<h2>${account?.trialUsed?'Welcome back.':'Your project is waiting.'}</h2><p>${esc(account?.email)}<br>Phone ending ${esc(account?.phoneEnding)} verified.</p><form data-form="checkout"><label class="consent-label"><input name="accepted" type="checkbox" required><span>I agree to the <a href="${esc(config.terms)}" target="_blank" rel="noopener">subscription terms</a> and authorize ${account?.trialUsed?'US$15/month plus applicable tax starting now':'US$15/month plus applicable tax after my 3-day free trial'}, automatically renewed until I cancel. ${account?.trialUsed?'':'I can cancel before the trial ends to avoid the first charge.'}</span></label><button class="button primary">${account?.trialUsed?'Subscribe for $15/month':'Continue to free-trial checkout'} →</button></form><small>Secure payment details are collected by Stripe. ${account?.trialUsed?'You’ve already used your free trial.':'The trial begins when you complete checkout.'}</small><div class="actions">${account?.hasCustomer?'<button class="textbutton" data-action="portal">Manage billing</button>':''}<button class="textbutton" data-action="logout">Sign out</button></div>`;
  if(stage==='account')html=`<p class="eyebrow">Account &amp; billing</p><h2>${account.access?'Make room for your next idea.':'Let’s get you back to building.'}</h2><dl class="account-facts"><div><dt>Email</dt><dd>${esc(account.email)}</dd></div><div><dt>Plan</dt><dd>Specly Studio · $15/month</dd></div><div><dt>Status</dt><dd>${esc(account.status.replaceAll('_',' '))}${account.cancelAtPeriodEnd?' · cancellation scheduled':''}</dd></div>${account.status==='trialing'?`<div><dt>Trial ends</dt><dd>${date(account.trialEnd)}</dd></div>`:`<div><dt>${account.cancelAtPeriodEnd?'Access until':'Current period ends'}</dt><dd>${date(account.periodEnd)}</dd></div>`}</dl><p>${account.status==='trialing'?(account.cancelAtPeriodEnd?'Your trial is scheduled to end without renewal.':'Your first charge is US$15 plus applicable tax when the trial ends. Cancel before then to avoid it.'):account.access?'Your subscription includes 45 projects: 15 beginner, 15 intermediate, and 15 advanced.':'Your plan does not currently include studio access. Open billing to review payment details or cancellation.'}</p><div class="actions">${account.access?'<a class="button primary" href="./">Open studio →</a>':''}<button class="button" data-action="portal">Manage billing / cancel</button><button class="textbutton" data-action="refresh">Refresh status</button><button class="textbutton" data-action="logout">Sign out</button></div><small>Receipts, payment details and cancellation are available in your billing portal. ${links()}</small>`;
  $('#account-card').innerHTML=html;$('#account-card').setAttribute('aria-busy','false');$('#membership-footer').innerHTML=links();
  if(stage==='email'&&config?.captchaKey)mountCaptcha();
}
async function mountCaptcha(){captchaToken='';if(!window.turnstile){await new Promise((resolve,reject)=>{let script=document.querySelector('#turnstile-script');if(script){script.addEventListener('load',resolve,{once:true});script.addEventListener('error',reject,{once:true});return}script=document.createElement('script');script.id='turnstile-script';script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.onload=resolve;script.onerror=reject;document.head.appendChild(script)}).catch(()=>message('Security check could not load. Refresh to try again.',true))}if(window.turnstile&&$('#captcha')){if(captchaWidget!==undefined)window.turnstile.remove(captchaWidget);captchaWidget=window.turnstile.render('#captcha',{sitekey:config.captchaKey,callback:token=>captchaToken=token,'expired-callback':()=>captchaToken='','error-callback':()=>captchaToken=''})}}
async function refresh(){try{account=await api('account');stage=!account.phoneVerified?'phone':account.pending||account.access?'account':'checkout'}catch(e){if(e.status===401){account=null;stage='email'}else throw e}render()}
document.addEventListener('submit',async event=>{
  const form=event.target.closest('[data-form]');if(!form)return;event.preventDefault();if(!config)return;
  const button=form.querySelector('button');button.disabled=true;message('Working…');const data=new FormData(form);
  try{
    if(form.dataset.form==='email'){address=String(data.get('email')).trim();await api('auth/email',{email:address,captchaToken});stage='email-code';render();message('Code sent. Check your spam folder if it doesn’t arrive.')}
    if(form.dataset.form==='email-code'){await api('auth/email/verify',{email:address,code:data.get('code')});await refresh();message('Email verified.')}
    if(form.dataset.form==='phone'){const result=await api('auth/phone',{phone:data.get('phone')});phone=result.phone;stage='phone-code';render();message('Verification code sent.')}
    if(form.dataset.form==='phone-code'){await api('auth/phone/verify',{phone,code:data.get('code')});await refresh();message('Phone verified. Review the terms before checkout.')}
    if(form.dataset.form==='checkout'){const result=await api('billing/checkout',{accepted:data.get('accepted')==='on',termsVersion:config.termsVersion});location.assign(result.url)}
  }catch(e){message(e.message,true);if(form.dataset.form==='email'&&window.turnstile&&captchaWidget!==undefined){window.turnstile.reset(captchaWidget);captchaToken=''}}finally{button.disabled=false}
});
document.addEventListener('click',async event=>{const button=event.target.closest('[data-action]');if(!button)return;button.disabled=true;try{
  const action=button.dataset.action;
  if(action==='email-again'){stage='email';render();message('')}
  if(action==='phone-again'){stage='phone';render();message('')}
  if(action==='refresh'){await refresh();message('Your billing status is up to date.')}
  if(action==='logout'){await api('auth/logout',{});account=null;stage='email';render();message('Signed out. Projects saved on this device remain here.')}
  if(action==='portal'){const result=await api('billing/portal',{});location.assign(result.url)}
}catch(e){message(e.message,true)}finally{button.disabled=false}});
try{
  const response=await fetch('./api/config');
  if(response.status===404||(response.ok&&!response.headers.get('content-type')?.includes('application/json'))){$('#mode-banner').innerHTML='<p class="mode-notice"><strong>Membership preview.</strong> Signups and payments aren’t active on this demo. No trial starts here and no charges can be made.</p>';render()}
  else{if(!response.ok)throw Error('The account service is unavailable. Please try again.');config=await response.json();if(config.mode==='test')$('#mode-banner').innerHTML='<p class="mode-notice"><strong>Test environment.</strong> Use test payment details only. No real charges are made.</p>';await refresh();if(new URLSearchParams(location.search).get('checkout')==='success')message(account?.access?'Your membership is ready. Welcome to Specly.':'Checkout returned. Refresh your status in a moment; access is confirmed with the billing provider.');if(new URLSearchParams(location.search).get('checkout')==='canceled')message('Checkout was not completed. No new trial was started here.')}
}catch(e){$('#account-card').innerHTML='<h2>We couldn’t connect.</h2><p>Refresh this page to try again. Your account and billing settings have not been changed.</p>';message(e.message,true)}
