import {samples,evaluateSample,sampleDiagram,sampleChart} from './sample-engine.js';
let active=-1,design={},tested=false;
const app=document.querySelector('#app');
const titleCase=s=>s[0].toUpperCase()+s.slice(1);
function membership(){return `<section class="panel demo-membership"><div><p class="eyebrow">Turn the sample into your own work</p><h2>Build your portfolio with Specly.</h2><p>Create a verified account and start your 3-day trial to choose from 45 member projects—15 at each difficulty—save your work, and export portfolio reports.</p><small>Payment method required. Then US$15/month plus applicable tax until canceled. Cancel before the trial ends to avoid the first charge.</small></div><a class="button primary" href="./commerce.html">View membership →</a></section>`}
function catalog(){return `<section class="intro"><div><div class="eyebrow">Engineering projects for internships & jobs</div><h1>Build engineering projects.<br><em>Put them on your portfolio.</em></h1><p>Get a focused brief, work through design decisions, and turn your tests into evidence you can discuss in an interview.</p></div></section><div class="sectionbar"><strong>Try a small sample</strong><span class="count">3 projects · one at each difficulty</span></div><p class="levelnote">Move the sliders, watch your design change, and test it against the brief. These three interactive samples are free to explore; saving, portfolio exports, and the full project library require a trial or membership.</p><div class="cards">${samples.map((s,i)=>`<article class="missioncard" style="--accent:${s.color}"><div class="cardtop"><span>${titleCase(s.level)}</span><span>Sample 0${i+1}</span></div><div class="diagram sample-card-diagram">${sampleDiagram(i,s.design)}</div><div class="cardbody"><h3>${s.title}</h3><p>${s.description}</p></div><div class="cardfoot"><span>Guided preview</span><button class="circlebutton" data-sample="${i}">Try sample →</button></div></article>`).join('')}</div>${membership()}`}
const number=(v,d=2)=>Number(v.toFixed(d)).toLocaleString('en-US');
function liveVisual(){const s=samples[active],r=evaluateSample(active,design);const metrics=s.type==='structure'?[['Tip deflection',r.metrics.deflection,'mm'],['Support mass',r.metrics.mass,'g'],['Safety factor',r.metrics.safety,'']]:s.type==='isolation'?[['Natural frequency',r.metrics.fn,'Hz'],['Motion transmission',r.metrics.T,'×'],['Static sag',r.metrics.sag,'mm']]:[['Source temperature',r.metrics.temp,'°C'],['Plate mass',r.metrics.mass,'g'],['Thermal resistance',r.metrics.R,'K/W']];return `<div class="viewport"><div class="viewtoolbar"><span>${s.type==='structure'?'Cantilever support':s.type==='isolation'?'Spring–damper mount':'Cooling plate'}</span><span>Live analytical preview</span></div><div class="diagram">${sampleDiagram(active,design)}</div><div class="viewcaption">Schematic · dimensions control the calculations; drawing is not to scale.</div><div class="readouts">${metrics.map(([label,value,unit])=>`<div class="readout"><span>${label}</span><strong>${number(value)} <small>${unit}</small></strong></div>`).join('')}</div></div><section class="panel sample-response"><h3>Watch the response change.</h3>${sampleChart(active,design,r)}<p class="note">${s.type==='isolation'?'The curve shows how much base motion reaches the payload across different excitation frequencies.':s.type==='structure'?'The curve shows predicted bending from the fixed root to the loaded tip.':'The curve shows predicted source temperature as heat input increases.'}</p></section>`}
function testResults(){if(!tested)return '<p>Move a slider to explore, then run a test to check this configuration.</p>';const r=evaluateSample(active,design);return `<p class="eyebrow">Sample results</p><h2>${r.pass?'Modeled requirements met.':'Room to improve.'}</h2><div class="checks">${r.checks.map(c=>`<div class="req"><span>${c.label}<small class="sample-limit">Required ${c.minimum?'≥':'≤'} ${number(c.limit,3)} ${c.unit}</small></span><strong>${number(c.value,3)} ${c.unit} · ${c.pass?'Pass':'Revise'}</strong></div>`).join('')}</div><p>${r.advice}</p>`}
function workspace(){const s=samples[active];return `<div class="workspacehead"><div><p class="eyebrow">${s.level} · interactive sample</p><h1>${s.title}</h1><p>${s.description}</p></div><button class="button ghost" data-back>All three samples</button></div><div class="workgrid"><section class="panel controls"><p class="eyebrow">The brief</p><h2>Try it. Change it. Test it.</h2><p>${s.context}</p>${s.controls.map(([key,label,min,max,step,unit])=>`<div class="field"><label for="sample-${key}">${label}<span><output id="value-${key}" for="sample-${key}">${design[key]}</output> ${unit}</span></label><input class="sample-slider" id="sample-${key}" type="range" data-param="${key}" min="${min}" max="${max}" step="${step}" value="${design[key]}" aria-label="${label}"><small>${min}–${max} ${unit}</small></div>`).join('')}<p class="note">${s.type==='isolation'?`Payload stays fixed at ${s.design.mass} kg.`:'Material stays fixed at 6061-T6 aluminum.'} This sample uses one fixed brief.</p><div class="actions"><button class="button primary" data-test>Run sample test →</button><button class="button ghost" data-reset>Reset design</button></div><p class="note">Nothing is saved. Leaving or refreshing resets your work.</p></section><div id="sample-visual">${liveVisual()}</div></div><section class="panel" id="sample-results" aria-live="polite">${testResults()}</section><details class="panel"><summary>Model assumptions and limitations</summary><p>${s.assumptions}</p></details><div class="sample-locked"><div><strong>Want to save this work or make a portfolio report?</strong><p>A verified account and active 3-day trial or membership are required.</p></div><a class="button" href="./commerce.html">Unlock saving & exports →</a></div>${membership()}`}
function render(){app.innerHTML=`<header class="topbar"><button class="brand" data-back>specly<small>Engineering for your portfolio</small></button><div class="topright"><span class="storage">Sample only · not saved</span><a class="button small" href="./commerce.html">Account & membership</a></div></header><main id="main" class="sample-main">${active<0?catalog():workspace()}<footer><span>Specly · Your work. Your decisions.</span><span>Educational analytical models</span></footer></main>`}
document.addEventListener('click',e=>{const sample=e.target.closest('[data-sample]');if(sample){active=Number(sample.dataset.sample);design={...samples[active].design};tested=false;render();window.scrollTo(0,0)}if(e.target.closest('[data-back]')){active=-1;design={};tested=false;render();window.scrollTo(0,0)}if(e.target.closest('[data-test]')){tested=true;document.querySelector('#sample-results').innerHTML=testResults()}if(e.target.closest('[data-reset]')){design={...samples[active].design};tested=false;render()}});
document.addEventListener('input',e=>{const key=e.target.dataset.param;if(active<0||!key)return;const next={...design,[key]:Number(e.target.value)};try{evaluateSample(active,next);design=next;tested=false;document.querySelector('#value-'+key).textContent=design[key];document.querySelector('#sample-visual').innerHTML=liveVisual();document.querySelector('#sample-results').innerHTML='<p>Design changed. Run a sample test to check this configuration.</p>'}catch{e.target.value=design[key]}});
render();
