import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import * as engine from '../studio/engine.js';
function harness(){const mission=engine.generateMission('structure','beginner',3);const design={length:140,width:30,thickness:8,material:'aluminum'};const project={id:'test-1',mission,design,runs:[{design:{...design},date:'2026-09-25T00:00:00Z'}],title:'Test <script>alert(1)</script>',notes:'Choice: <b>thicker</b> & lighter.',measurement:'',observations:'',created:'2026-09-25T00:00:00Z'};const node={innerHTML:'',textContent:'',classList:{add(){},remove(){}}};const context=vm.createContext({...engine,crypto:{randomUUID:()=> 'test-2'},localStorage:{getItem:()=>JSON.stringify([project]),setItem(){}},document:{querySelector:()=>node,addEventListener(){}},window:{scrollTo(){}},setTimeout:()=>0,clearTimeout(){},console});const code=fs.readFileSync(new URL('../studio/app.js',import.meta.url),'utf8').replace(/^import .*?;\n/,'');vm.runInContext(code,context);vm.runInContext('download=(filename,content,type)=>{globalThis.captured={filename,content,type}}',context);return context;}
test('report escapes authored text and accurately labels simulation-only work',()=>{const c=harness();vm.runInContext('report(projects[0])',c);assert.ok(c.captured.content.includes('&lt;script&gt;alert(1)&lt;/script&gt;'));assert.ok(!c.captured.content.includes('<script>alert(1)</script>'));assert.ok(c.captured.content.includes('No physical measurement recorded'));assert.ok(c.captured.content.includes('5/5 analytical checks passed'));assert.equal(c.captured.type,'text/html')});
test('report uses last verified configuration rather than untested edits',()=>{const c=harness();vm.runInContext('projects[0].design.thickness=2;report(projects[0])',c);assert.ok(c.captured.content.includes('140 × 30 × 8 mm'));assert.ok(!c.captured.content.includes('140 × 30 × 2 mm'));assert.ok(c.captured.content.includes('Untested workspace changes are excluded'))});
test('physical evidence is labeled self-reported and included verbatim after escaping',()=>{const c=harness();vm.runInContext("projects[0].measurement='0.3';projects[0].observations='Measured with dial indicator';report(projects[0])",c);assert.ok(c.captured.content.includes('Self-reported, not independently verified'));assert.ok(c.captured.content.includes('Measured with dial indicator'))});
test('revision limit preserves existing history rather than deleting evidence',()=>{const c=harness();vm.runInContext('projects[0].runs=Array.from({length:100},()=>projects[0].runs[0])',c);assert.throws(()=>vm.runInContext('runTest()',c),/100 recorded tests/);assert.equal(vm.runInContext('projects[0].runs.length',c),100)});
