export const materials={aluminum:{name:'6061-T6 aluminum',E:69e9,yield:276e6,rho:2700,k:167},steel:{name:'Mild steel',E:200e9,yield:250e6,rho:7850,k:50},titanium:{name:'Ti-6Al-4V',E:114e9,yield:880e6,rho:4430,k:6.7}};
export const families={
structure:{name:'Structural supports',short:'Structures',title:'Keep the payload steady.',description:'Design a lightweight cantilever support. Balance stiffness, strength, and mass.',code:'STR',time:'30–60 min',color:'#176c58',scenes:['Field-mapping drone','Autonomous inspection rover','Portable optical instrument'],context:'A field instrument needs a lightweight support to hold its sensor clear of the main chassis. Excessive bending will disturb its measurements.',params:[['length','Reach',80,220,5,'mm'],['width','Section width',15,65,1,'mm'],['thickness','Section thickness',2,12,.5,'mm']],defaults:{length:140,width:30,thickness:3,material:'aluminum'},assumptions:'Uniform rectangular Euler–Bernoulli cantilever; perfectly fixed root; static tip load; isotropic linear-elastic material. No self-weight, holes, joint compliance, torsion, fatigue, buckling, impact, or manufacturing defects. Slender-beam and small-deflection assumptions must hold. Material values are typical educational values, not design allowables.',equations:['I = bt³ / 12','σmax = 6FL / (bt²)','δtip = FL³ / (3EI)','m = ρLbt; FoS = σyield / σmax'],hint:'Thickness changes bending stiffness cubically, but mass only linearly. Shortening the reach helps too—if the mission allows it.',build:['Create a dimensioned drawing of the rectangular support and its mounting arrangement.','Select stock and plan cutting, edge finishing, and clamping with your shop supervisor.','Apply known static loads in increments; measure tip displacement without exceeding the planned elastic load.','Plot load versus displacement and compare the slope with the model. Document clamp flexibility.'],measure:'Measured tip deflection (mm)',reference:'https://ocw.mit.edu/courses/2-080j-structural-mechanics-fall-2013/'},
isolation:{name:'Vibration isolation',short:'Dynamics',title:'Separate signal from shake.',description:'Tune a spring–damper mount to protect a sensitive instrument from vibration.',code:'DYN',time:'40–70 min',color:'#7855a6',scenes:['Rover instrument platform','Workshop inspection camera','Mobile air-quality sensor'],context:'A sensitive instrument rides on a vibrating base. Design an equivalent spring–damper mount that reduces motion at the operating frequency without sagging too far under gravity.',params:[['stiffness','Total spring stiffness',200,6000,50,'N/m'],['damping','Damping ratio',.03,.6,.01,''],['mass','Supported payload',.5,3,.1,'kg']],defaults:{stiffness:3000,damping:.2,mass:1.5},assumptions:'Linear single-degree-of-freedom vertical mount under steady sinusoidal base excitation. Stiffness is the combined stiffness of all springs. Constant viscous damping. No rotations, nonlinear elastomers, transient shock, or travel-stop impacts. Resonance during startup must be assessed separately.',equations:['fn = √(k/m) / (2π); r = f / fn','T = √[(1 + (2ζr)²) / ((1 − r²)² + (2ζr)²)]','xstatic = mg / k','c = 2ζ√(km)'],hint:'Isolation begins above a frequency ratio of √2. Softer springs improve high-frequency isolation but increase static sag. More damping controls resonance, yet can transmit more motion at high frequencies.',build:['Specify the payload, spring arrangement, total stiffness, damping target, and available travel.','Measure static sag with the actual payload to estimate the assembled spring stiffness.','Measure base and payload motion using calibrated sensors at the operating frequency.','Compare amplitude ratio to the model and inspect startup resonance and available travel.'],measure:'Measured amplitude ratio',reference:'https://ocw.mit.edu/courses/2-003sc-engineering-dynamics-fall-2011/pages/mechanical-vibration/'},
thermal:{name:'Passive cooling',short:'Thermal',title:'Give the heat a way out.',description:'Size a flat cooling plate for electronics operating in ambient air.',code:'THM',time:'30–50 min',color:'#a95625',scenes:['Outdoor sensor node','Remote data logger','Bench-top controller'],context:'An electronics module must reject heat to ambient air without a fan. Size a plate that stays below a temperature limit while fitting within the mass and packaging envelope.',params:[['length','Plate length',60,260,5,'mm'],['width','Plate width',60,220,5,'mm'],['thickness','Plate thickness',1,8,.5,'mm']],defaults:{length:120,width:100,thickness:3,material:'aluminum'},assumptions:'Steady-state lumped isothermal plate with convection from two unobstructed large faces. Constant prescribed h; uniform heat input over one face; one-dimensional through-thickness conduction. Edges, radiation, contact resistance, local hot spots, fin effects, and heat spreading are excluded. Air cooling only; not applicable in vacuum.',equations:['A = Lb; Aconv = 2A','Rθ = t / (kA) + 1 / (hAconv)','Tsource = Tambient + QRθ','m = ρLbt'],hint:'Exposed area is the strongest lever in this simplified model. Thickness adds mass and through-thickness resistance; this model cannot capture the heat-spreading benefits of a thicker real plate.',build:['Draw the plate and explain how both large faces remain exposed to air.','Specify the heater footprint, attachment, temperature sensor locations, and insulation.','At the specified power and ambient temperature, wait for steady state and record temperatures.','Compare the measured rise with the prediction; discuss contact resistance and uncertainty in convection.'],measure:'Measured source temperature (°C)',reference:'https://ntrs.nasa.gov/citations/20230013900'}
};
export function generateMission(type,level='beginner',seed=1){if(!Number.isSafeInteger(seed)||seed<0)throw Error('Invalid mission seed');if(!families[type]||!['beginner','intermediate','advanced'].includes(level))throw Error('Invalid mission selection');if(seed>=1000000&&seed<1000045)return memberMission(type,level,seed);const d=['beginner','intermediate','advanced'].indexOf(level),v=Math.abs(Math.floor(seed))%3;const common={type,level,seed,id:`${families[type].code}-${String(seed%10000).padStart(4,'0')}`,scene:families[type].scenes[v]};return {...common,requirements:type==='structure'?{force:18+d*12+v*3,maxMass:125-d*15,maxDeflection:1.2-d*.25,minSafety:2+d*.25,minReach:110+d*15}:type==='isolation'?{frequency:18+d*4+v*2,maxTransmission:.35-d*.07,maxSag:12-d*2,payload:1.5+v*.2}: {power:6+d*2+v,maxTemp:65-d*3,ambient:25+v*2,h:8,maxMass:300-d*30,maxLength:240-d*10}};}
export function validateDesign(type,p){const f=families[type];if(!f)throw Error('Unknown category');for(const [key,,min,max] of f.params){if(typeof p[key]!=='number'||!Number.isFinite(p[key])||p[key]<min||p[key]>max)throw Error(`Invalid ${key}`);}if(type!=='isolation'&&!materials[p.material])throw Error('Choose a valid material');return true;}
const check=(label,value,limit,unit,minimum=false)=>({label,value,limit,unit,minimum,pass:minimum?value>=limit:value<=limit});
export function transmissibility(r,z){return Math.sqrt((1+(2*z*r)**2)/((1-r*r)**2+(2*z*r)**2));}
export function evaluate(m,p){validateDesign(m.type,p);const q=m.requirements;let metrics,checks,curve,advice; if(m.type==='structure'){const a=materials[p.material],L=p.length/1000,b=p.width/1000,t=p.thickness/1000,I=b*t**3/12,stress=6*q.force*L/(b*t*t),deflection=q.force*L**3/(3*a.E*I)*1000,mass=a.rho*L*b*t*1000,safety=a.yield/stress;metrics={stress:stress/1e6,deflection,mass,safety};checks=[check('Tip deflection',deflection,q.maxDeflection,'mm'),check('Support mass',mass,q.maxMass,'g'),check('Yield safety factor',safety,q.minSafety,'',true),check('Required reach',p.length,q.minReach,'mm',true),check('Beam slenderness (L/t)',p.length/p.thickness,10,'',true)];curve=Array.from({length:41},(_,i)=>{const x=L*i/40;return [x*1000,q.force*x*x*(3*L-x)/(6*a.E*I)*1000]});advice=deflection>q.maxDeflection?'The support is too flexible. Try increasing thickness before adding width.':mass>q.maxMass?'Mass is driving this design. Try a lighter material or reduce width while checking stiffness.':'Review the remaining requirements and document the tradeoffs behind your section choice.';
}else if(m.type==='isolation'){const fn=Math.sqrt(p.stiffness/p.mass)/(2*Math.PI),ratio=q.frequency/fn,T=transmissibility(ratio,p.damping),sag=p.mass*9.80665/p.stiffness*1000;metrics={fn,ratio,T,sag,c:2*p.damping*Math.sqrt(p.stiffness*p.mass)};checks=[check('Motion transmission',T,q.maxTransmission,'×'),check('Static sag',sag,q.maxSag,'mm'),check('Payload difference',Math.abs(p.mass-q.payload),.001,'kg')];curve=Array.from({length:81},(_,i)=>{const f=i*.75;return[f,transmissibility(f/fn,p.damping)]});advice=T>q.maxTransmission?'Too much vibration reaches the payload. Reduce stiffness to move the natural frequency below the operating frequency.':sag>q.maxSag?'The mount sags too far. Increase stiffness, then recheck motion transmission.':'Document how you would measure damping and handle resonance during startup.';
}else{const a=materials[p.material],L=p.length/1000,b=p.width/1000,t=p.thickness/1000,A=L*b,R=t/(a.k*A)+1/(q.h*2*A),temp=q.ambient+q.power*R,mass=a.rho*L*b*t*1000;metrics={temp,mass,R,area:2*A*1e4};checks=[check('Source temperature',temp,q.maxTemp,'°C'),check('Plate mass',mass,q.maxMass,'g'),check('Packaging length',p.length,q.maxLength,'mm')];curve=Array.from({length:41},(_,i)=>{const power=q.power*1.5*i/40;return [power,q.ambient+power*R]});advice=temp>q.maxTemp?'Increase exposed area to reduce the convection resistance. Confirm that both faces will actually see air.':mass>q.maxMass?'Reduce thickness or select a lower-density material; then rerun the temperature check.':'Plan a physical temperature test: real convection and contact resistance may change the result.';}return {metrics,checks,curve,advice,pass:checks.every(c=>c.pass),passed:checks.filter(c=>c.pass).length};}
export function initialDesign(m){return {...families[m.type].defaults,...(m.type==='isolation'?{mass:m.requirements.payload}:{})};}

const memberLevels=['beginner','intermediate','advanced'];
// Five application briefs per model family, with a distinct application and
// numerical envelope at each level. These are analytical project studies.
const memberBriefs=[
  ['structure',['Desk camera support','Rover inspection-camera boom','Precision optical alignment arm'],['Hold a small camera beyond the edge of a desk-mounted frame.','Keep an inspection camera clear of a rover chassis under a larger static payload.','Position alignment optics on a long lightweight arm with a tight displacement budget.']],
  ['structure',['Weather-sensor bracket','Drone air-sampling support','Mapping payload cantilever'],['Support a weather sensor away from its mounting post.','Extend a sampling head beyond a drone frame using a simplified static load case.','Trade mass against stiffness for an extended mapping payload support.']],
  ['structure',['Lab indicator arm','Materials-test probe holder','Precision metrology extension'],['Hold a dial indicator over a small laboratory specimen.','Position a test probe where bending of its holder could contaminate measurements.','Design a low-mass extension for metrology equipment and quantify bending sensitivity.']],
  ['structure',['Workbench light support','Inspection-light extension','Remote inspection sensor arm'],['Support a task light at a required distance from a workbench clamp.','Keep an inspection light above a component while meeting a tighter mass allowance.','Carry a sensor beyond an inspection fixture with competing reach and deflection limits.']],
  ['structure',['Classroom robot sensor tab','Conveyor detector bracket','Automated inspection probe boom'],['Mount a small detector beyond a classroom robot base.','Position a conveyor detector outside the machine frame under a defined static load.','Develop a long probe boom for an automated fixture and defend its structural tradeoffs.']],
  ['isolation',['Desk instrument isolator','Rover accelerometer platform','Precision imaging isolation stage'],['Reduce steady vibration transmitted from a benchtop to an instrument.','Isolate a rover-mounted measurement package at a prescribed operating frequency.','Tune an imaging platform with tight isolation and static-sag constraints.']],
  ['isolation',['Workshop camera mount','Machine-vision camera isolator','High-frequency inspection camera mount'],['Investigate how a spring-mounted camera responds to a vibrating base.','Keep a machine-vision payload stable near a running machine.','Balance high-frequency isolation against gravity sag for a heavier inspection camera.']],
  ['isolation',['Tabletop sensor platform','Portable spectrometer isolator','Field spectroscopy isolation package'],['Choose the combined stiffness of springs supporting a tabletop sensor.','Reduce periodic base motion reaching a portable spectrometer.','Specify a compact isolation package for field spectroscopy and assess startup resonance.']],
  ['isolation',['Small electronics isolation tray','Mobile air-quality instrument mount','Survey electronics vibration platform'],['Support an electronics tray while limiting vibration transmission.','Tune a mobile air-quality instrument mount for its specified payload and excitation.','Protect a survey-electronics payload from harmonic base vibration within a tight sag budget.']],
  ['isolation',['Demonstration payload mount','Optical bench transport isolator','Precision payload isolation study'],['Compare spring and damping choices in a simple payload-isolation demonstration.','Investigate an optical payload mount using a steady harmonic transport surrogate.','Map the feasible stiffness-damping region for a heavy precision payload.']],
  ['thermal',['LED module cooling plate','Inspection-light heat spreader','High-power imaging-light cooling plate'],['Size a flat plate to reject heat from a small lighting module in ambient air.','Fit an inspection-light cooling plate inside a defined mass and length envelope.','Balance thermal resistance and mass for an imaging-light plate at higher heat input.']],
  ['thermal',['Sensor-node cooling plate','Outdoor monitoring electronics plate','Remote environmental station cooling plate'],['Cool a sensor module using two exposed plate faces and no fan.','Reject heat from monitoring electronics in a warmer ambient environment.','Keep a remote-station electronics plate below its limit with competing packaging constraints.']],
  ['thermal',['Bench controller heat plate','Motor-controller cooling study','Compact actuator electronics cooling plate'],['Explore how exposed area affects a small controller cooling plate.','Size a controller plate under a steady heat-load approximation.','Compare plate materials and dimensions for compact actuator electronics in ambient air.']],
  ['thermal',['Data-logger heat plate','Field acquisition module cooling plate','High-duty data-acquisition cooling study'],['Keep a small data logger below its specified steady temperature limit.','Design a passive cooling plate for a field-acquisition module.','Assess steady-state cooling for a high-duty acquisition system and plan a temperature test.']],
  ['thermal',['Communication module cooling plate','Ground receiver cooling plate','Dense telemetry electronics cooling plate'],['Reject heat from a low-power communications module without a fan.','Trade exposed area and mass for a ground receiver cooling plate.','Develop a cooling plate for dense telemetry electronics in warm terrestrial air.']]
];
function memberMission(type,level,seed){
  const index=seed-1000000,d=Math.floor(index/15),slot=index%15;
  const [family,names,contexts]=memberBriefs[slot],v=slot%5;
  if(type!==family||level!==memberLevels[d])throw Error('Project selection does not match its difficulty or category');
  const requirements=type==='structure'?{force:18+d*10+v*3,maxMass:150-d*15-v*3,maxDeflection:1.4-d*.25-v*.08,minSafety:2+d*.25,minReach:100+d*10+v*5}:type==='isolation'?{frequency:18+d*6+v*2,maxTransmission:.4-d*.06-v*.01,maxSag:14-d*2-v*.5,payload:1+v*.3}:{power:5+d*2+v,maxTemp:72-d*3,ambient:22+v*2,h:8,maxMass:350-d*25-v*10,maxLength:250-v*5};
  return {type,level,seed,id:`${families[type].code}-${['B','I','A'][d]}${String(slot+1).padStart(2,'0')}`,scene:names[d],context:contexts[d],requirements,deliverables:[
    'A baseline design, two recorded improvements, an explanation of the governing requirement, and a portfolio report.',
    'Three alternatives, a quantitative tradeoff comparison, a chosen design with supporting calculations, and a physical test plan.',
    'A parameter sensitivity study, a justified feasible design, a critique of model uncertainty, and an instrumented validation plan.'
  ][d]};
}
export function memberProjects(level='beginner'){
  const d=memberLevels.indexOf(level);if(d<0)throw Error('Invalid project difficulty');
  return memberBriefs.map(([type],i)=>memberMission(type,level,1000000+d*15+i));
}

// Curated rotation over the existing bounded library, not newly authored or AI
// generated content. UTC Mondays give everyone the same weekly collection.
export function weeklyCollection(date=new Date()) {
  const time=new Date(date);if(!Number.isFinite(time.getTime()))throw Error('Invalid collection date');
  const day=Date.UTC(time.getUTCFullYear(),time.getUTCMonth(),time.getUTCDate());
  const monday=day-((time.getUTCDay()+6)%7)*86400000;
  const week=Math.floor((monday-Date.UTC(2020,0,6))/604800000);
  const index=Math.max(0,week);
  return {starts:new Date(monday).toISOString(),next:new Date(monday+604800000).toISOString(),seeds:Object.fromEntries(Object.keys(families).map((type,i)=>[type,index*3+(index+i)%3]))};
}
